// Playground:
// https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgSwLYOAgbtAvFAzsRAOwHMoAfKAIwHtqAbCAQ0PKkIFclKI5WO66rdoQAmEAGYJCEEQChZoSFACiADwKMAxsAAq4CLgBicakgDK1dnE0QAPBas2ANFB2M4xCMAB8UHAG9ZKCgAbQBpKCkoAGsIEGpxV3dPYChGXCgIiHUIUQzY+MSHa2gAfkyoAC42CEw4AF1KoOCkjy9w+qhs4FyRDPhkVAwIZpaocqycvJi4hKhim1Gx8fnLEo6lserpOs2q1pSOrqm+qH9Qgur8ImJGtMIQKABfPeCJ457pgrmFkeXl8pqDTaPSQIwmcxrGz2KEQDouNxtYAdbyvFrbWo8NEY3YvBT6FTqOBaHoiUEGPyE4G6fTg0y-WzNc6MbbsAQAbiopVZHKgmmq500AEYeYIns8nEy0qLOfy2Gy6C4RKLnrJUbJsmBqHBUppqIR8B9idoZNUgcbSeSMgFmiz5QJJcFKKLHVAAPRuvku2RPIA
// https://www.typescriptlang.org/play?#code/C4TwDgpgBACgTgSwLYOAgbtAvFAzsRAOwHMoAfKAIwHtqAbCAQ0PKkIFclKI5WO66rdoQAmEAGYJCEEQChZAegVRQkKAFEAHgUYBjYABVwEXADE41JAGVq7OLogAeG3YcAaKAcZxiEYAD4oHABvRWUoKABtAGkoKSgAawgQanFPb19gKEZcKFiIbQhRXKSUtJd7aAB+PKgALjYITDgAXTqwiM6vHz8YlqgC4CKRXPhkVAwIDs7OmvzC4sTk1KgKh2mZ2dXbSr6NzfrG5v3Ohu7MvoGFkahgqNKG-CJiNuzCECgAXxOZuauhxalFZrKZKA6bGpaHT6IyQMwWaw7BzOJEQPoec69aItfw-TYNaTHMHgw6Engdb6yVTQKFwPSGYzwywglGuCAYjJ+QIhWQRGJxFhAtKYrI5WqDYYlZblVFQP4Epo8Nq8zrzAE3IXbNkq35a3bY-6S2CIFBoTA6iF6hx7EkNEGXCWLO6RB54AhSF4NZgfb4kiKQ7R0mGM8zM1Gs-UtDk9YB9XF+0mKuAWiIK44HWSU6lW7C3FWMBoABgA3CrKEXSxEwboGqEq+EoLoAIxFlVg76UsHZkVBPPE7INJul-s1qBNtwbESDift+Rd4waQP0mSwky92n01dMxFsiPudIx3EdApgahwLK6aiEfD-INDKeL6H3re90L9gtQQszhvlz-fzrVkW-6UieZ5ZOIwj6AgV6NnATBDCKjgGIaiwgv4AAUwCcsAZwAJQNBuwZwqGO6VHu7KeIEdZQHBwB2CwWExtkuTCAkhDUAA7iwYqEQyxEIiyIIYrilKXteWSMZkva6HBjAIdh6HUR+X5lkBKqjtRETNq2ESfBOEQPipny4XOygAEp+PRKgABbQJecBwfoKiMh4lDsFkIjUCYhAAORZDwFi8DBugeM2HjMCIUAiAAdLFVILgYJhZDg1IrJJfimc5ajWew1nrkuREmCRgmoh4b4NhEynDhVVAVicGl4lpLZsJw3BwNVmyfB1MwPhwXA8B1ny4kAA
import {
  DesignTokens,
  DesignToken,
  DesignTokenAlias,
  DesignTokenGroup,
} from './types'

type Creator<Base> = <T extends Base>(val: T) => T

export const createDesignTokens: Creator<DesignTokens> = (val) => val
export const createDesignToken: Creator<DesignToken> = (val) => val
export const createDesignTokenAlias: Creator<DesignTokenAlias> = (val) => val
export const createDesignTokenGroup: Creator<DesignTokenGroup> = (val) => val
